name: stats
description: A new Flutter application 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  badge: ^0.0.3
  chewie: ^0.8.0
  flutter_youtube: ^1.1.4
  super_tooltip: ^0.9.0
  date_format: ^1.0.5
  photo_view: ^0.1.2
  cloud_firestore: ^0.7.4
  dragablegridview_flutter: ^0.1.2
  firebase_storage: ^1.0.4
  flutter_list_drag_and_drop: ^0.1.6
  flutter_multiple_image_picker: ^0.0.1
  hidden_drawer_menu: ^0.2.0
  flutter_facebook_login: ^1.1.1
  firebase_auth: ^0.6.6
  flutter_signin_button: ^0.2.5
  flutter_auth_buttons: ^0.3.1
  google_sign_in: 3.2.4
  flutter_twitter_login: ^1.1.0
  flutter_tags: ^0.1.6
  flutter_form_builder: ^1.3.4
  flutter_rating: ^0.0.2
  smooth_star_rating: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/menu.png
    - images/trending.png
    - images/notification.png
    - images/search.png
    - images/profile.png
    - images/profile1.png
    - images/createVote.png
    - images/plan.jpg
    - images/share.png
    - images/home.png
    - images/megaphone.png
    - images/cast.png
    - images/info.png
    - images/lock.png
    - images/plan.jpg
    - images/exit.png
    - images/vote.png
    - images/background.jpg
    - images/background1.jpg
    - images/picker.png
#    - images/background2.jpg
#    - images/background3.jpg
    - images/pollBox.jpg
    - images/yes.png
    - images/refresh.png
    - images/long_press.png
    - images/assets/berlin.png
    - images/assets/delhi.png
    - images/assets/london.png
    - images/assets/newyork.png
    - images/assets/paris.png
    - images/assets/vancouver.png
    - images/nominee_images/nominee0.jpg
    - images/nominee_images/nominee1.jpg
    - images/nominee_images/nominee2.jpg
    - images/nominee_images/nominee3.jpg
    - images/nominee_images/nominee4.jpg
    - images/nominee_images/nominee5.jpg
    - images/nominee_images/nominee6.jpg
    - images/nominee_images/nominee7.jpg
    - images/nominee_images/nominee8.jpg
    - images/nominee_images/nominee9.jpg
    - images/nominee_images/nominee10.jpg
    - images/loader.gif
    - images/loader2.gif
    - images/full-bloom.png
    - images/facebook.png
    - images/twitter_sign_in.png
    - images/assets/images.jpg
    - images/google_sign_in.png
    - images/pick.gif
    - images/createVoteBack1.jpg
    - images/createVoteBack2.jpg
    - images/createVoteBack2.jpg

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
