name: stats
description: A new Flutter application 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  badge: ^0.0.3
  chewie: ^0.9.6
#  flutter_youtube: ^1.1.6
  super_tooltip: ^0.9.0
  date_format: ^1.0.5
  photo_view: ^0.1.2
  cloud_firestore: ^0.7.4
  dragablegridview_flutter: ^0.2.0
  firebase_storage: ^1.0.4
  flutter_list_drag_and_drop: ^0.1.6
  flutter_multiple_image_picker: ^0.0.1
  hidden_drawer_menu: ^0.2.0
  flutter_facebook_login: ^1.1.1
  firebase_auth: ^0.6.6
  flutter_signin_button: ^0.2.5
  flutter_auth_buttons: ^0.3.1
  google_sign_in: 3.2.4
  flutter_twitter_login: ^1.1.0
  flutter_tags: ^0.1.7
  flutter_form_builder: ^1.3.4
  flutter_rating: ^0.0.2
  smooth_star_rating: ^1.0.1
  emoji_feedback: ^0.1.0
  custom_radio: ^0.1.2
  flutter_circular_chart: ^0.1.0
  random_color: ^1.0.3
  intro_views_flutter: ^2.4.0
  multi_page_form: ^1.0.4
  toggle_button: ^1.0.0
  flutter_range_slider: ^1.1.0
  date_range_picker: ^1.0.3
  datetime_picker_formfield: ^0.1.8
  material_switch: ^0.0.5
  expandable: ^2.0.0
  cupertino_range_slider: ^1.0.1
  flutter_google_places_autocomplete: ^0.1.3
  vertical_tabs: ^0.1.4
  material_search: ^0.2.8
#  adv_image_picker: ^0.1.1
  custom_multi_image_picker: ^2.1.24
  medias_picker: ^0.1.2
  flutter_svg: ^0.12.0
  stack_overlay: ^0.1.1
  gradient_widgets: ^0.3.1
  flushbar: ^1.3.0
  loader_search_bar: ^1.0.3+3
  flutter_slidable: ^0.4.9
  flutter_fluid_slider: ^0.0.1
  folding_cell: ^0.1.2
  simple_countdown: ^0.0.1
  sqflite: ^1.1.0
  reorderables: ^0.2.0
  flutter_advanced_networkimage: ^0.4.15
#  google_maps_flutter: ^0.2.0+3
#  multi_image_picker: ^3.0.22
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  badge: ^0.0.3

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/menu.png
    - images/trending.png
    - images/notification.png
    - images/search.png
    - images/profile.png
    - images/profile1.png
    - images/createVote.png
    - images/plan.jpg
    - images/share.png
    - images/home.png
    - images/megaphone.png
    - images/cast.png
    - images/info.png
    - images/lock.png
    - images/plan.jpg
    - images/exit.png
    - images/vote.png
    - images/background.jpg
    - images/background1.jpg
    - images/picker.png
    - images/background2.jpg
    - images/background3.jpg
    - images/pollBox.jpg
    - images/yes.png
    - images/refresh.png
    - images/long_press.png
    - images/assets/berlin.png
    - images/assets/delhi.png
    - images/assets/london.png
    - images/assets/newyork.png
    - images/assets/paris.png
    - images/assets/vancouver.png
    - images/nominee_images/nominee0.jpg
    - images/nominee_images/nominee1.jpg
    - images/nominee_images/nominee2.jpg
    - images/nominee_images/nominee3.jpg
    - images/nominee_images/nominee4.jpg
    - images/nominee_images/nominee5.jpg
    - images/nominee_images/nominee6.jpg
    - images/nominee_images/nominee7.jpg
    - images/nominee_images/nominee8.jpg
    - images/nominee_images/nominee9.jpg
    - images/nominee_images/nominee10.jpg
    - images/loader.gif
    - images/loader2.gif
    - images/full-bloom.png
    - images/facebook.png
    - images/twitter_sign_in.png
    - images/assets/images.jpg
    - images/google_sign_in.png
    - images/pick.gif
    - images/createVoteBack1.jpg
    - images/createVoteBack11.png
    - images/createVoteBack2.jpg
    - images/createVoteBack2.jpg
    - images/currencies.png
    - images/next.png
    - images/previous.png
    - images/submit.png
    - images/facebook.svg
    - images/twitter.svg
    - images/google.svg
    - images/finalcountdown.jpg
    - images/count.png
    - images/birds.jpg
    - images/avatar.jpg
    - images/back1.jpg
    - images/back2.jpg
    - images/back3.jpg
    - images/back4.jpg
    - images/back5.jpg
    - images/back6.jpg
    - images/back7.jpg
    - images/back8.jpg
    - images/back9.jpg
    - images/back10.jpg
    - images/submited.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
